server:
  port: 9000

spring:
  application:
    name: loans

  profiles:
    active: qa

  datasource:
    url: jdbc:postgresql://localhost:5432/*
    driver-class-name: org.postgresql.Driver
    username: *
    password: *

  jpa:
    show-sql: true

  sql:
    init:
      mode: always

  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"

loans:
  buildVersion: "3.0"
  message: "Welcome to JaryqLibrary Loans related Dev APIs"
  contactDetails:
    name: "Ali Kenesbek - Developer"
    email: "ali_kenesbek@jaryqlibrary.com"
  onCallSupport:
    - "+7-555-1234"
    - "+7-555-5678"