server:
  port: 9000

spring:
  application:
    name: loans

  datasource:
    url: jdbc:postgresql://localhost:5432/*
    driver-class-name: org.postgresql.Driver
    username: *
    password: *

  jpa:
    show-sql: true

  sql:
    init:
      mode: always

loans:
  buildVersion: "2.0"
  message: "Welcome to JaryqLibrary Loans Microservice"
  contactDetails:
    name: "Ali Kenesbek"
    email: "ali_kenesbek@jaryqlibrary.com"
  onCallSupport:
    - "+7-555-1234"
    - "+7-555-5678"