server:
  port: 8080

spring:
  application:
    name: books

  datasource:
    url: jdbc:postgresql://localhost:5432/*
    driver-class-name: org.postgresql.Driver
    username: *
    password: *

  jpa:
    show-sql: true

  sql:
    init:
      mode: always

books:
  buildVersion: "1.0"
  message: "Welcome to JaryqLibrary Books Microservice"
  contactDetails:
    name: "Ali Kenesbek"
    email: "ali_kenesbek@jaryqlibrary.com"
  onCallSupport:
    - "+7-555-1234"
    - "+7-555-5678"
