server:
  port: 9010

spring:
  application:
    name: message

  cloud:
    function:
      definition: sendMemberCreated;sendLoanCreated
    stream:
      bindings:
        sendMemberCreated-in-0:
          destination: send-member-created
          group: ${spring.application.name}
        sendMemberCreated-out-0:
          destination: member-created-sent

        sendLoanCreated-in-0:
          destination: send-loan-created
          group: ${spring.application.name}
        sendLoanCreated-out-0:
          destination: loan-created-sent
      kafka:
        binder:
          brokers:
            - localhost:9092