server:
  port: 8090

spring:
  application:
    name: members

  datasource:
    url: jdbc:postgresql://localhost:5432/*
    driver-class-name: org.postgresql.Driver
    username: *
    password: *

  jpa:
    show-sql: true

  sql:
    init:
      mode: always