services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  books-db:
    container_name: books-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: booksdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  members-db:
    container_name: members-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: membersdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loans-db:
    container_name: loans-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  rabbit:
    image: rabbitmq:4-management
    container_name: rabbit
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "bekasyl04/configserver-library:2.0.0"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  eurekaserver:
    image: "bekasyl04/eurekaserver-library:2.0.0"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  books:
    image: "bekasyl04/books-library:2.0.0"
    container_name: book-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "books"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://books-db:5432/booksdb"
    depends_on:
      books-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  members:
    image: "bekasyl04/members-library:2.0.0"
    container_name: member-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "members"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://members-db:5432/membersdb"
    depends_on:
      members-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  loans:
    image: "bekasyl04/loans-library:2.0.0"
    container_name: loan-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://loans-db:5432/loansdb"
    depends_on:
      loans-db:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  gatewayserver:
    image: "bekasyl04/gatewayserver-library:2.0.0"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    depends_on:
      redis:
        condition: service_healthy
      books:
        condition: service_healthy
      members:
        condition: service_healthy
      loans:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  jaryqlibrary:
    driver: "bridge"